// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPDiXdQ6R5rPSY17EqCsgug_bZxf1-Yt4',
    appId: '1:925527396820:web:3fa4ce833f481b28764641',
    messagingSenderId: '925527396820',
    projectId: 'smart-road-services',
    authDomain: 'smart-road-services.firebaseapp.com',
    storageBucket: 'smart-road-services.appspot.com',
    measurementId: 'G-L7EPGX9TMW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-9M-5X66xMp3uzVjE6f1IWrNhxABh474',
    appId: '1:925527396820:android:5cf0d4675a56237d764641',
    messagingSenderId: '925527396820',
    projectId: 'smart-road-services',
    storageBucket: 'smart-road-services.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADNoyYIOyU3FOD970sHgrJIjTv__7yEa8',
    appId: '1:925527396820:ios:2db7408f808e8707764641',
    messagingSenderId: '925527396820',
    projectId: 'smart-road-services',
    storageBucket: 'smart-road-services.appspot.com',
    iosBundleId: 'com.example.mistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADNoyYIOyU3FOD970sHgrJIjTv__7yEa8',
    appId: '1:925527396820:ios:672238a64f5b98ad764641',
    messagingSenderId: '925527396820',
    projectId: 'smart-road-services',
    storageBucket: 'smart-road-services.appspot.com',
    iosBundleId: 'com.example.mistApp.RunnerTests',
  );
}
